/*
Deployment script for SAEIS
This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "SAEIS"
:setvar DefaultFilePrefix "SAEIS"
:setvar DefaultDataPath "D:\Program Files\Microsoft SQL Server\MSSQL15.SAEON2019\MSSQL\DATA\"
:setvar DefaultLogPath "D:\Program Files\Microsoft SQL Server\MSSQL15.SAEON2019\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


--GO
--IF EXISTS (SELECT 1
--           FROM   [master].[dbo].[sysdatabases]
--           WHERE  [name] = N'$(DatabaseName)')
--    BEGIN
--        ALTER DATABASE [$(DatabaseName)]
--            SET TEMPORAL_HISTORY_RETENTION ON 
--            WITH ROLLBACK IMMEDIATE;
--    END


GO
PRINT N'Starting rebuilding table [dbo].[Images]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Images] (
    [ImageID]          INT             IDENTITY (1, 1) NOT NULL,
    [Type]             NVARCHAR (MAX)  NULL,
    [SubType]          NVARCHAR (MAX)  NULL,
    [Name]             NVARCHAR (MAX)  NULL,
    [Code]             NVARCHAR (MAX)  NULL,
    [ImageDate]        NVARCHAR (MAX)  NULL,
    [LinkToImage]      NVARCHAR (MAX)  NULL,
    [LinkToHiResImage] NVARCHAR (1000) NULL,
    [HiResImageSize]   BIGINT          NULL,
    [Available]        NVARCHAR (1)    NULL,
    [Source]           NVARCHAR (MAX)  NULL,
    [Reference]        NVARCHAR (MAX)  NULL,
    [Notes]            NVARCHAR (MAX)  NULL
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Images])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Images] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Images] ([ImageID], [Type], [SubType], [Name], [Code], [ImageDate], [LinkToImage], [Available], [Source], [Reference], [Notes])
        SELECT [ImageID],
               [Type],
               [SubType],
               [Name],
               [Code],
               [ImageDate],
               [LinkToImage],
               [Available],
               [Source],
               [Reference],
               [Notes]
        FROM   [dbo].[Images];
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Images] OFF;
    END

DROP TABLE [dbo].[Images];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Images]', N'Images';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Update complete.';


GO