CREATE TABLE [dbo].[Estuary] (
    [EstuaryID]                       INT            NOT NULL,
    [EstuaryNum]                      INT            NULL,
    [EstuaryKZN]                      NVARCHAR (1)   NULL,
    [EstuaryName]                     NVARCHAR (MAX) NOT NULL,
    [AlternativeName]                 NVARCHAR (MAX) NULL,
    [ProvinceID]                      INT            NULL,
    [Place]                           NVARCHAR (MAX) NULL,
    [Distance]                        DECIMAL (9, 3) NULL,
    [LatitudeDegrees]                 INT            NULL,
    [LatitudeMinutes]                 INT            NULL,
    [LatitudeSeconds]                 INT            NULL,
    [LatitudeDecimalDegrees]          DECIMAL (9, 6) NULL,
    [LongitudeDegrees]                INT            NULL,
    [LongitudeMinutes]                INT            NULL,
    [LongitudeSeconds]                INT            NULL,
    [LongitudeDecimalDegrees]         DECIMAL (9, 6) NULL,
    [ClassificationID]                INT            NULL,
    [ClassificationDate]              NVARCHAR (MAX) NULL,
    [HarrisonClassification]          INT            NULL,
    [WhitfieldClassification]         INT            NULL,
    [ManagementClassificationID]      INT            NULL,
    [GeomorphologyID]                 INT            NULL,
    [BioRegionID]                     INT            NULL,
    [WaterQualityID]                  INT            NULL,
    [ConditionID]                     INT            NULL,
    [ConditionDate]                   NVARCHAR (MAX) NULL,
    [ConditionRemarks]                NVARCHAR (MAX) NULL,
    [InfoAvailableID]                 INT            NULL,
    [MunicipalityID]                  INT            NULL,
    [BreachExistID]                   INT            NULL,
    [BreachNeedID]                    INT            NULL,
    [MouthOpen]                       INT            NULL,
    [AreaFloodplain]                  DECIMAL (9, 3) NULL,
    [AreaWater]                       DECIMAL (9, 3) NULL,
    [AreaCatchment]                   INT            NULL,
    [AreaCatchmentDEAT]               INT            NULL,
    [LengthShoreline]                 DECIMAL (9, 3) NULL,
    [LengthRiver]                     INT            NULL,
    [MARunnoff]                       INT            NULL,
    [MinFlowReq]                      INT            NULL,
    [SelectionStatus]                 INT            NULL,
    [OverallRank]                     INT            NULL,
    [NationalConsImp]                 NVARCHAR (MAX) NULL,
    [ProvincialConsImp]               NVARCHAR (MAX) NULL,
    [Notes]                           NVARCHAR (MAX) NULL,
    [RankConsImp]                     INT            NULL,
    [SizeConsImp]                     INT            NULL,
    [ZonalRarityConsImp]              INT            NULL,
    [HabitatConsImp]                  INT            NULL,
    [BiodiversityConsImp]             DECIMAL (9, 3) NULL,
    [ScoreConsImp]                    DECIMAL (9, 3) NULL,
    [DemandCatRDM]                    NVARCHAR (MAX) NULL,
    [DemandScoreRDM]                  INT            NULL,
    [ImpCatRDM]                       NVARCHAR (MAX) NULL,
    [ImpScoreRDM]                     DECIMAL (9, 3) NULL,
    [PriorityRDM]                     INT            NULL,
    [BiblioWitfieldLink]              NVARCHAR (MAX) NULL,
    [TempOrthos]                      NVARCHAR (MAX) NULL,
    [PercentAgriculture]              INT            NULL,
    [PercentDegraded]                 INT            NULL,
    [PercentNatural]                  INT            NULL,
    [PecentUrban]                     INT            NULL,
    [LandcoverReference]              NVARCHAR (MAX) NULL,
    [SancutaryProtectionID]           INT            NULL,
    [UndevelopedMarginID]             INT            NULL,
    [WaterRequirementID]              INT            NULL,
    [PriorityForRehabilitationID]     INT            NULL,
    [WaterQualityPollution]           NVARCHAR (1)   NULL,
    [WaterQualitySilt]                NVARCHAR (1)   NULL,
    [WaterQuantityGen]                NVARCHAR (1)   NULL,
    [AlienClearing]                   NVARCHAR (1)   NULL,
    [FixAppropriateBankStabilisation] NVARCHAR (1)   NULL,
    [MouthManagement]                 NVARCHAR (1)   NULL,
    [RehabilitationComments]          NVARCHAR (MAX) NULL
);

